version: '3.5'

services:
  lumen:
    ports:
      - "9999:9999"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    build: .
    command: php -S lumen:9999 -t public
    restart: always
